services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Maispace\MaiTimeline\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Maispace\MaiTimeline\Indexer\TimelineIndexer:
    tags:
      - name: 'maispace.search.indexer'
      - name: 'maispace.search.result_formatter'
